import type { HistoryPoint } from './stats';
import type { ItemEntry } from './item';

export type PlayerSummary = {
  uuid: string;
  username: string;
  last_seen: string;
  online: boolean;
  activity?: PlayerActivity;
  play_time_hours: number;
  rank: 'admin' | 'vip' | 'member';
  deaths: number;
  kills: number;
  mob_kills: number;
  player_kills: number;
  blocks_mined: number;
  distance_meters: number;
  jumps: number;
};

export type PlayerActivity = {
  first_seen: string;
  last_seen: string;
  last_join: string;
  last_quit: string;
  last_session_hours: number;
  active_now_hours: number;
  playtime_hours: number;
  total_recorded_delta_hours: number;
};

export type PlayerFull = PlayerSummary & {
  first_joined: string;
  blocks_placed: number;
  blocks_broken: number;
  blocks_crafted: number;
  deaths: number;
  kills: number;
  damage_dealt: number;
  damage_taken: number;
  damage_blocked_by_shield: number;
  jumps: number;
  leave_game: number;
  sleep_in_bed: number;
  sneak_time_hours: number;
  sprint_meters: number;
  walk_meters: number;
  swim_meters: number;
  fly_meters: number;
  climb_meters: number;
  fall_meters: number;
  boat_meters: number;
  minecart_meters: number;
  horse_meters: number;
  items_picked_up: number;
  items_dropped: number;
  items_used: number;
  items_broken: number;
  items_crafted_total: number;
  animals_bred: number;
  fish_caught: number;
  talked_to_villager: number;
  traded_with_villager: number;
  interacted_with_crafting_table: number;
  open_chest: number;
  items_traded: number;
  balance: number;
  achievements: string[];
  top_mined: Array<{ id: string; count: number }>;
  top_used: Array<{ id: string; count: number }>;
  top_crafted: Array<{ id: string; count: number }>;
  top_picked_up: Array<{ id: string; count: number }>;
  top_dropped: Array<{ id: string; count: number }>;
  top_killed: Array<{ id: string; count: number }>;
  top_killed_by: Array<{ id: string; count: number }>;
  inventory_snapshot?: ItemEntry[];
  stats_history: HistoryPoint[];
};
